"""How many configurations have actually been tested, and on what.

Answers one question with no hedging: what has this project measured. Every count comes from
results/coverage/coverage.json, which is itself generated by scanning results/ against the
declaration in configs/psbd_basis.json, so nothing here is typed by hand.

    PYTHONPATH=. python scripts/vit_config_inventory.py --out docs/psbd-vit-configs-tested.md
"""

import argparse
import collections
import json


def load(path):
    with open(path) as handle:
        return json.load(handle)


def build(ledger, declaration):
    cells = ledger["cells"]
    placements = ledger["placements"]
    basis = declaration["basis"]
    basis_ids = {entry["id"] for entry in basis}
    clearing = [c for c in cells if c["asr_class"] == "clears"]

    distinct = {row["placement"] for row in placements}
    rate_units = sum(row["n_complete_rates"] for row in placements)
    by_operator = collections.Counter(
        row["perturbation"] or "unknown" for row in placements
    )
    by_position = collections.Counter(
        row["position_config"] or "unknown" for row in placements
    )
    banded = sum(1 for row in placements if row["block_range"])
    seeds = collections.Counter(row["mask_seed"] for row in placements)

    out = []
    w = out.append
    w("# PSBD-ViT: how many configurations have been tested")
    w("")
    w(
        "Generated by `scripts/vit_config_inventory.py` from `results/coverage/coverage.json`."
    )
    w("Do not edit by hand.")
    w("")
    w(f"- generated: {ledger['generated_at']}")
    w("")
    w("## Headline")
    w("")
    w("| quantity | count |")
    w("|---|---:|")
    w(f"| checkpoints in the ViT all-to-one panel | {len(cells)} |")
    w(
        f"| of those, attacks that actually implanted (ASR >= {ledger['asr_bar']}) | {len(clearing)} |"
    )
    w(
        f"| **declared basis configurations, measured on every implanted cell** | **{len(basis)}** |"
    )
    w(f"| distinct placements ever cached anywhere | {len(distinct)} |")
    w(f"| total (cell, placement) measurements on disk | {len(placements)} |")
    w(f"| total (cell, placement, rate) sweeps on disk | {rate_units} |")
    w(
        f"| pre-registered combinations of basis placements | "
        f"{len(declaration['combinations']['pairs'])} explicit + "
        f"{declaration['combinations']['derived_triples']['count']} derived |"
    )
    w("")
    w(
        "A configuration is a **position**, an **operator** and a **block range**. The three are"
    )
    w(
        "independent, so the count that matters is the basis: the fixed set measured on EVERY"
    )
    w(
        "cell, which is what makes cells comparable. Before that basis existed, no placement was"
    )
    w(
        "cached on all cells and rankings were computed over whichever cells happened to carry a"
    )
    w("placement, which ranks the cells rather than the placements.")
    w("")

    w("## Basis coverage per cell")
    w("")
    histogram = collections.Counter(c["n_basis_covered"] for c in cells)
    w("| basis configurations measured | cells |")
    w("|---:|---:|")
    for covered in sorted(histogram, reverse=True):
        marker = "  (complete)" if covered == len(basis) else ""
        w(f"| {covered}{marker} | {histogram[covered]} |")
    w("")
    complete = sum(1 for c in clearing if c["n_basis_covered"] == len(basis))
    w(
        f"**{complete} of {len(clearing)}** cells whose attack implanted carry the complete basis."
    )
    w(
        "The cells below the basis are the ones whose attack did not implant, which are being"
    )
    w(
        "retrained; sweeping a checkpoint that is about to be replaced throws the work away."
    )
    w("")

    w("## The 18 basis configurations")
    w("")
    w("| # | position | operator | blocks | family | rates swept |")
    w("|---:|---|---|---|---|---:|")
    for index, entry in enumerate(basis, start=1):
        band = (
            f"{entry['block_range'][0]}-{entry['block_range'][1]}"
            if entry["block_range"]
            else "all 12"
        )
        w(
            f"| {index} | `{entry['position_config']}` | `{entry['perturbation']}` | {band} | "
            f"{entry['family']} | {len(entry['rates'])} |"
        )
    w("")

    w("## What has been swept, by axis")
    w("")
    w("| operator | (cell, placement) measurements |")
    w("|---|---:|")
    for operator, count in by_operator.most_common():
        w(f"| `{operator}` | {count} |")
    w("")
    w("| position | (cell, placement) measurements |")
    w("|---|---:|")
    for position, count in by_position.most_common():
        w(f"| `{position}` | {count} |")
    w("")
    w(
        f"Band-restricted measurements (a depth range rather than all 12 blocks): **{banded}**."
    )
    w("")
    w("| perturbation mask seed | measurements |")
    w("|---:|---:|")
    for seed, count in sorted(
        seeds.items(), key=lambda item: (item[0] is None, item[0])
    ):
        w(f"| {seed} | {count} |")
    w("")
    w(
        "Seed 0 is the canonical draw. Non-zero seeds are repeat draws of the same estimator,"
    )
    w("measuring its run-to-run spread rather than a different configuration.")
    w("")

    w("## Still to measure")
    w("")
    gaps = collections.Counter()
    for cell in cells:
        if cell["asr_class"] != "clears":
            gaps[cell["attack"]] += len(basis) - cell["n_basis_covered"]
    if gaps:
        w("| attack | basis slots outstanding | reason |")
        w("|---|---:|---|")
        for attack, count in gaps.most_common():
            w(f"| {attack} | {count} | attack under the ASR bar, retraining first |")
        w("")
    w("Nothing outstanding on any cell whose attack implanted.")
    w("")
    return "\n".join(out) + "\n"


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--coverage", default="results/coverage/coverage.json")
    parser.add_argument("--declaration", default="configs/psbd_basis.json")
    parser.add_argument("--out", default="docs/psbd-vit-configs-tested.md")
    return parser.parse_args()


def main():
    args = parse_args()
    text = build(load(args.coverage), load(args.declaration))
    with open(args.out, "w") as handle:
        handle.write(text)
    print(f"[ok] {args.out}  ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
