"""Render the findings registry with its macros substituted and its evidence checked.

paper/findings.md names numbers by macro so it cannot drift from the tables.
This writes paper/findings.rendered.md with every macro replaced by its value
from headline.json, marks a macro headline.tex does not define and marks an
evidence path that does not exist under the results tree or the repository.

    PYTHONPATH=. python scripts/paper/findings_index.py --results-dir results
"""

import os
import re
import sys

sys.path.insert(0, os.getcwd())

from scripts.paper._common import GRADES, build_parser, load_json  # noqa: E402
from utils.provenance import utc_timestamp  # noqa: E402

COLUMNS = (
    "id",
    "hypotheses",
    "claim",
    "grade",
    "evidence",
    "generator",
    "status",
    "draft",
)


def registry_rows(path: str) -> list[dict]:
    """The table rows of findings.md as dicts, header and rule rows skipped."""
    rows = []
    with open(path) as handle:
        for line in handle:
            if (
                not line.startswith("|")
                or line.startswith("|---")
                or line.startswith("| id")
            ):
                continue
            cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
            if len(cells) != len(COLUMNS):
                raise SystemExit(
                    f"a findings row has {len(cells)} cells, expected {len(COLUMNS)}: {line}"
                )
            rows.append(dict(zip(COLUMNS, cells)))
    return rows


def substitute(claim: str, macros: dict) -> tuple[str, list[str]]:
    """The claim with every `\\Macro` replaced by its value, and the undefined ones."""
    undefined = []

    def replace(match):
        name = match.group(1)
        if name in macros:
            return macros[name]["value"]
        undefined.append(name)
        return f"[undefined \\{name}]"

    rendered = re.sub(r"`?\\([A-Za-z]+)`?", replace, claim)
    return rendered, undefined


def evidence_exists(evidence: str, results_dir: str) -> bool:
    """Whether every path in a comma-separated evidence field exists somewhere expected."""
    exists = True
    for item in [
        part.strip().strip("`") for part in evidence.split(",") if part.strip()
    ]:
        candidates = (item, os.path.join(results_dir, item.removeprefix("results/")))
        if not any(os.path.exists(candidate) for candidate in candidates):
            exists = False
    return exists


def main() -> int:
    args = build_parser(__doc__).parse_args()
    registry = os.path.join(args.paper_dir, "findings.md")
    macros = load_json(os.path.join(args.paper_dir, "headline.json")) or {}
    rows = registry_rows(registry)

    problems = []
    lines = [
        "# Findings, rendered",
        "",
        f"Generated by scripts/paper/findings_index.py at {utc_timestamp()} from findings.md "
        "and headline.json. Do not edit by hand.",
        "",
        "| id | grade | claim | status | draft | evidence |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        if row["grade"] not in GRADES:
            problems.append(
                f"{row['id']}: grade {row['grade']!r} is not one of {GRADES}"
            )
        rendered, undefined = substitute(row["claim"], macros)
        problems += [f"{row['id']}: macro \\{name} undefined" for name in undefined]
        evidence_mark = (
            "" if evidence_exists(row["evidence"], args.results_dir) else " (missing)"
        )
        lines.append(
            f"| {row['id']} | {row['grade']} | {rendered} | {row['status']} | {row['draft']} | "
            f"{row['evidence']}{evidence_mark} |"
        )
        if evidence_mark:
            problems.append(f"{row['id']}: evidence not found: {row['evidence']}")
    lines.append("")
    with open(os.path.join(args.paper_dir, "findings.rendered.md"), "w") as handle:
        handle.write("\n".join(lines))

    for problem in problems:
        print(problem)
    print(f"{len(rows)} findings rendered, {len(problems)} problems")
    status = 1 if problems else 0
    return status


if __name__ == "__main__":
    sys.exit(main())
