"""Fold every generator's macro sidecar into paper/headline.tex and paper/headline.json.

A number that appears in prose is a \\newcommand here, written by the generator
that computed it, so the prose cannot drift from the table. headline.json keeps
the provenance beside every macro.

    PYTHONPATH=. python scripts/paper/headline.py
"""

import glob
import json
import os
import sys

sys.path.insert(0, os.getcwd())

from scripts.paper._common import TABLES_DIR, build_parser, load_json  # noqa: E402
from utils.provenance import current_git_commit, utc_timestamp  # noqa: E402


def main() -> None:
    args = build_parser(__doc__).parse_args()
    tables_dir = os.path.join(args.paper_dir, os.path.basename(TABLES_DIR))
    sidecars = sorted(glob.glob(os.path.join(tables_dir, "*.macros.json")))

    macros = {}
    for path in sidecars:
        payload = load_json(path)
        for name, entry in payload["macros"].items():
            if name in macros and macros[name]["value"] != entry["value"]:
                raise SystemExit(
                    f"macro {name} defined twice with different values, in "
                    f"{macros[name]['generator']} and {payload['generator']}"
                )
            macros[name] = {
                **entry,
                "generator": payload["generator"],
                "inputs": payload["inputs"],
            }

    tex_lines = [
        f"% generated by scripts/paper/headline.py from {len(sidecars)} sidecars at "
        f"{utc_timestamp()}, commit {current_git_commit()}. Do not edit by hand.",
    ]
    for name in sorted(macros):
        tex_lines.append(
            f"\\newcommand{{\\{name}}}{{{macros[name]['value']}}}  % {macros[name]['meaning']}"
        )
    tex_lines.append("")
    with open(os.path.join(args.paper_dir, "headline.tex"), "w") as handle:
        handle.write("\n".join(tex_lines))
    with open(os.path.join(args.paper_dir, "headline.json"), "w") as handle:
        json.dump(macros, handle, indent=2)
    print(f"{len(macros)} macros from {len(sidecars)} generators")


if __name__ == "__main__":
    main()
